### ISSUE TITLE
关于模型预测问题

### ISSUE THREAD

**Issue by YanZiBuGuiCHunShiWan** [thu-coai/PsyQA#4]
您好，我对模型的推理有一点疑惑。就是论文中提到微调模型时用了strategy策略，就是句子前面添加了特殊的token，那么在训练时模型也会预测到这些特殊的token啊，所以模型推理时也会预测到这些特殊的token吧？论文中提供的模型回复的图片中的案例是已经把这些特殊token删除掉了么？

**Comment by TissueC** [comment]
是的，已经删除掉了，用颜色来表示。

**Comment by YanZiBuGuiCHunShiWan** [comment]
好的，感谢！😊



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月16日(周一) 下午5:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [thu-coai/PsyQA] 关于模型预测问题 (Issue #4)




 
是的，已经删除掉了，用颜色来表示。
